# ───────────────────── nav2_params.yaml ─────────────────────

# Global costmap parameters
global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 1.0
      width: 10
      height: 10
      resolution: 0.1
      robot_radius: 0.30
      lethal_cost_threshold: 200

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        footprint_clearing_enabled: true
        combination_method: 1
        scan:
          topic: /scan
          obstacle_max_range: 3.0
          obstacle_min_range: 0.0
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          expected_update_rate: 5.0 
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35
        cost_scaling_factor: 15.0 # default: 10.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      update_frequency: 5.0
      publish_frequency: 1.0
      resolution: 0.03

# Controller, planner, BT, lifecycle manager
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_dist: 0.5
      use_collision_detection: true


planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      allow_unknown: true

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "behavior_trees_navigator/navigation.xml"
    transform_tolerance: 0.5
    bt_loop_duration: 20

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - map_server
      - global_costmap
      - local_costmap
      - planner_server
      - controller_server
      - bt_navigator
      - waypoint_follower
      - velocity_smoother
