# ─── Laser Filter ───────────────────────────────────────────────
scan_filter_chain:
  ros__parameters:
    scan_filter_chain:
      - name: range_filter
        type: laser_filters/LaserScanRangeFilter
        params:
          use_message_range_limits: false
          lower_threshold:         0.05
          upper_threshold:         8.0      # clamp ∞ just above SLAM max
          lower_replacement_value: 0.05
          upper_replacement_value: 8.1


# config/scan_filter_params.yaml

# scan_filter_chain:
#   ros__parameters:
#     scan_filter_chain:
#       # 1) throw away anything whose 'intensity' is too low
#       - name: quality_filter
#         type: laser_filters/LaserScanQualityFilter
#         params:
#           # tune this above your scanner’s noise floor
#           quality_threshold: 2.0
#           # remove the entire beam when < threshold
#           keep_invalid:       false

#       # 2) clamp any < 0.1 m or > 8.0 m → 8.1 m (slam ignores 8.1 m as 'out of range')
#       - name: range_filter
#         type: laser_filters/LaserScanRangeFilter
#         params:
#           use_message_range_limits: false
#           lower_threshold:          0.1     # anything closer than 10 cm
#           upper_threshold:          8.0     # anything beyond SLAM max
#           lower_replacement_value:  8.1
#           upper_replacement_value:  8.1

#       # 3) a quick median pass to smooth any leftover one-off spikes
#       - name: median_filter
#         type: laser_filters/LaserScanMedianFilter
#         params:
#           window_size: 5           # 5-beam median window
