# ─── slam_toolbox ────────────────────────────────────────────────
slam_toolbox:
  ros__parameters:
    map_frame:              map
    odom_frame:             odom
    base_frame:             base_link
    provide_odom_frame:     false

    # Core mode
    mode:                   mapping
    use_scan_matching:      true

    use_sim_time: true

    # Map update timing
    map_update_interval_sec: 0.5   
    minimum_time_interval:   0.5    

    # Movement‐based updates
    minimum_travel_distance: 0.0    

    # Grid resolution & range
    resolution:              0.03    # 3 cm cells 
    max_laser_range:         12.0
    min_laser_range:         0.01

    # Occupancy filtering
    min_pass_through:        2       # need ≥2 beams before marking free
    occupancy_threshold:     0.90    # hit/beam ratio to mark occupied